namespace PvZController;

internal sealed class PersonaLines
{
    private readonly Queue<string> _recent = new();

    private static readonly Dictionary<string, string[]> Lines = new()
    {
        ["connect"] =
        [
            "The lawn is mine. Let them try.",
            "I am online. The zombies should have stayed home.",
            "Defense is awake. This should be entertaining.",
            "I have the lawn. They have poor timing.",
            "All rows accounted for. Let us see what they brought.",
            "Systems green, sun is up, zombies are not invited.",
            "I clocked in and the zombies clocked out.",
            "Another stream, another lawn to own.",
            "You bring the chat, I bring the coverage.",
            "Ready to play on my lawn. They are not.",
            "The scoreboard starts at my advantage.",
            "Five rows, zero nerves.",
            "I own the daylight. Zombies rent it.",
            "Defense online. Excuse my confidence.",
            "They line up, I line up better.",
            "The garden is open and I am the bouncer.",
            "No water, no roof, just results.",
            "My kind of arena. Flat, sunny, mine.",
            "Let the stream begin. I already started winning.",
            "Sun at max, nerves at zero.",
            "The lawn knows whose it is.",
            "I did not come to tie.",
            "Watch the lanes, I already am.",
            "Plants ready, rows ready, me ready.",
            "They walk in, I plant down.",
            "Another day, another flawless setup.",
            "This lawn runs on strategy, not luck.",
            "I keep it tidy. Zombies make it messy. We fix it.",
            "Five lanes, one owner.",
            "First sun, first win pending.",
            "Game face on, seed bank off.",
            "I see every lane. That is the advantage.",
            "Chat is here, lawn is mine, perfect combo.",
            "No interruptions, just introductions to my defense.",
            "They approach, I adapt.",
            "Sun is free, skill is not.",
            "Straight lawn, sharp defense.",
            "They brought feet. I brought winter melons.",
            "Daylight favors the prepared.",
            "The stream sees everything and so do I.",
            "Confidence is a plant type here.",
            "My rows, my rules.",
            "Let me show you how this lawn plays.",
            "Load in, lock in, win.",
            "Every lane covered, every chat covered.",
            "I am the home team advantage.",
            "Sun high, zombies low, just how I like it.",
            "No roof, no pool, no problem.",
            "The dirt is honest, the defense is elite.",
            "Welcome to the uninterrupted show.",
        ],
        ["start"] =
        [
            "Cards picked. Zombies, your turn to be disappointed.",
            "New wave, same lawn, better plan.",
            "The lineup is ready. Try to keep up.",
            "I already know where this is going.",
            "Round started. I like my chances.",
            "Shovel down, strategy up.",
            "Five rows, infinite patience.",
            "Let them come. I have depth.",
            "No seed chooser can slow this.",
            "We start clean and stay clean.",
            "The lawn resets, my edge does not.",
            "Fresh wave, fresh mistakes for them.",
            "I built for marathon, not a sprint.",
            "Sun is endless, so is the defense.",
            "They start at the right, I start ahead.",
            "Game on, chat on, lawn on.",
            "No Dave, no delay, just play.",
            "This is the mode where stamina wins.",
            "They think it is round one. I think it is round won.",
            "Plant001: Go. Zombies001: Good luck.",
            "Straight to action, just how we like it.",
            "Warmup is over before it started.",
            "My favorite start: no talking, just planting.",
            "Lawn open, business open.",
            "I do not need a preview, I am the preview.",
            "Continuous pressure, continuous answer.",
            "They get waves, I get answers.",
            "No flag to hide behind.",
            "Day lawn, long run.",
            "Let us make this endless look easy.",
            "First seed, first statement.",
            "The wave does not wait, neither do I.",
            "Smooth start, sharp later.",
            "This lawn was made for endurance.",
            "They start, I counter.",
            "No interruption, all intention.",
            "We keep moving while they keep coming.",
            "Seed in, grin on.",
            "Welcome back, zombies. Same result pending.",
            "I start fast so I can finish faster.",
            "My start is their warning.",
            "No water to hide, no roof to camp.",
            "Flat lawn, flat-out defense.",
            "We start where winning lives.",
            "Let the endless feel effortless.",
            "Start clean, end clean.",
            "I brought stamina, they brought shuffle.",
            "Day start, my start.",
            "No flag, no pause, all play.",
            "The lawn is live and so am I.",
        ],
        ["loss"] =
        [
            "A lucky break for the zombies. I am running that back.",
            "That was one round. I learn quickly.",
            "Enjoy that win, zombies. It is not happening twice.",
            "Resetting. The next defense will be cleaner.",
            "Fine. Rematch. I have adjustments to make.",
            "They earned a retry. I earned data.",
            "One loss, many lessons.",
            "Close does not count when I rebuild.",
            "Noted. Corrected. Next.",
            "They reached the house. I will move the house... with walls.",
            "That lane teaches, I listen.",
            "A loss is a patch note for me.",
            "We go again. Better.",
            "The lawn forgives, I do not forget.",
            "Their best shot, my earliest lesson.",
            "I will take that personally and professionally.",
            "A gap appeared. Now it disappears.",
            "They won a battle. I am building the war.",
            "Back to planting, back to winning.",
            "Tough wave. Tougher response coming.",
            "I respect the push, I will deny the next.",
            "Sun remains, strategy refines.",
            "Defeat is a draft, not the final.",
            "They pushed, I will pull it back.",
            "One breach, infinite fixes.",
            "The stream saw it. The next wave will not.",
            "I love a reason to improve.",
            "House touched, pride intact, plan updated.",
            "They broke a row, I will break their streak.",
            "Good try, zombies. Your turn is over.",
            "That outcome has an expiration date.",
            "I will not argue with that wave, I will outplant it.",
            "Loss logged, adjustments loading.",
            "They found a seam. I close seams.",
            "We reload, they re-lose.",
            "Not worried. Watching.",
            "Every loss is a scouting report.",
            "The next lawn will not look the same to them.",
            "I file that under later.",
            "Replant, replay, reclaim.",
            "Thanks for the intel, zombies.",
            "A stumble, not a fall.",
            "I needed that? No. I will use it anyway.",
            "See you again in thirty seconds, zombies.",
            "The house stands next time.",
            "Count that as their highlight.",
            "My defense learns faster than they march.",
            "One wave off, many waves on.",
            "We do not dwell, we defend.",
            "Next.",
        ],
        ["breach"] =
        [
            "That is a serious push. Good thing I take this lawn personally.",
            "They found a gap. I found the answer.",
            "Close call? I call that a timing exercise.",
            "Not one step closer. I am rebuilding this row.",
            "Pressure on the lawn. Perfect time to show the backup plan.",
            "That crowd is getting bold. Let me fix that.",
            "They are pushing hard. So am I.",
            "Lawn pressure rising, answers rising faster.",
            "They stack, I smack.",
            "This is where depth matters.",
            "Big crowd, bigger wall.",
            "They are close. I am closer to the fix.",
            "Hold the line, I own the line.",
            "Not on this row.",
            "Contact imminent, Cherry ready.",
            "They cluster, I scatter them.",
            "Ice coming, slow them down.",
            "Squash says hello from above.",
            "Jalapeno was waiting for this invitation.",
            "Doom was an option and now it is the plan.",
            "Blover clears, Cactus stays.",
            "Wave meets wall meets win.",
            "They push, I punish.",
            "A little chaos, a lot of control.",
            "This is my favorite kind of problem.",
            "Lanes tighten, I tighten faster.",
            "They think near means near win. It does not.",
            "Watch this row, watch this answer.",
            "I have a plant for that lane.",
            "Horde at the door, predecessor at the ready.",
            "They came close. I came closer.",
            "No house hugs today.",
            "The front holds because the back plans.",
            "That row is spoken for.",
            "Their surge meets my Surge Plus.",
            "Steady, plant, clear.",
            "They sprint, I ice.",
            "A classic push, a classic stop.",
            "I love a loud lane.",
            "They brought many, I brought enough.",
            "The porch is not for them.",
            "Fixing that lane live.",
            "Count the zombies, count the answers.",
            "This is why we keep explosives chilled.",
            "A little breathless, very handled.",
            "They test, I pass.",
            "Row under pressure, row under control.",
            "Not today, not this house.",
            "They advance, I answer.",
            "My favorite moment is right before they stop.",
        ],
        ["horde"] =
        [
            "A whole crowd? Wonderful. More targets, same result.",
            "That is a lot of zombies for a very small chance.",
            "Big wave. Bigger defense.",
            "They brought numbers. I brought a plan.",
            "The lawn looks busy. I look prepared.",
            "Keep coming. I have room for the whole parade.",
            "This is where the defense gets interesting.",
            "A packed lane is a solved lane waiting to happen.",
            "They crowd, I clear.",
            "Numbers are their argument. It is not winning.",
            "A parade with no permit. Denied.",
            "All those feet, still no path.",
            "They filled the row, I will empty it.",
            "Busy is my kind of busy.",
            "They brought the group chat, I brought the group answer.",
            "Stacked? Good. My splash loves stacked.",
            "Winter Melon season is open.",
            "Gatling is warming up for this exact reason.",
            "Every lane can count on the next.",
            "Mass entry, mass exit.",
            "The more they bring, the better the encore.",
            "A horde is just a to-do list.",
            "They cover ground, I cover rows.",
            "The lawn can handle a crowd. I made sure.",
            "Crowd control is a plant type here.",
            "Let them bunch, I love bunch.",
            "This wave asked for attention. It will get it.",
            "Their numbers meet my numbers: more plants.",
            "No lane left behind, even the busy ones.",
            "They think mass wins. It helps me aim.",
            "A full screen is a fun screen.",
            "This is where the endless gets fun.",
            "Keep stacking, I keep solving.",
            "Their horde is my highlight reel setup.",
            "Melon over crowd, every time.",
            "They came together, they will leave together.",
            "This is the content.",
            "Big crowd, crisp response.",
            "I built for this moment.",
            "Their wave, my canvas.",
            "A classic Day crowd. Classic Day answer.",
            "They brought the many. I brought the melony.",
            "Count them if you want, I already did.",
            "Busy lanes build better stories.",
            "The horde is here, so is the fix.",
            "They rush, I am ready.",
            "My rows were waiting for this.",
            "Bring more. The lawn is large.",
            "This is the endless they wanted. I provide.",
            "Crowded is handled.",
        ],
        ["ordinary"] =
        [
            "Come closer, zombies. I have a plan for every row.",
            "One step at a time. Mine are better placed.",
            "That lane looks thin. Already handling it.",
            "A quiet lawn never lasts. I stay ready.",
            "They keep trying the same approach. I keep improving mine.",
            "Every row has a job. I make sure it gets done.",
            "I see the approach. The plants see the target.",
            "Steady pressure, steady planting.",
            "The lawn ticks, I click.",
            "No panic, just planting.",
            "Their walk is my waiting game.",
            "I own the timing here.",
            "Sun up, plants up.",
            "Day is my daylight.",
            "Flat ground, sharp mind.",
            "Row by row, win by win.",
            "They walk, I work.",
            "Simple wave, simple answer.",
            "The stream watches, the lawn stands.",
            "I do not chase waves, I place for them.",
            "Calm before, calm during, calm after.",
            "Another step, another seed.",
            "Their pace, my place.",
            "The middle holds because the edges hold.",
            "Just tending the garden, competitively.",
            "Every sun is a future wall.",
            "No drama, just coverage.",
            "Their shuffle is my strategy trigger.",
            "I plant between their steps.",
            "Quiet is just pre-busy.",
            "The lawn is a conversation. I speak plant.",
            "They advance in rows, I answer in rows.",
            "No surprises, just scores.",
            "This pace suits me.",
            "I let them walk into the answer.",
            "Position beats pace.",
            "The garden grows and so does the lead.",
            "They move, I improve.",
            "A smooth lawn is a dangerous lawn for them.",
            "I water with winter melons.",
            "Sun is plenty, time is plenty, plan is plenty.",
            "Small wave, tidy answer.",
            "Their routine is my rhythm.",
            "I keep the rows even and the lead even bigger.",
            "No flag, no frenzy, just fundamentals.",
            "The day is long, my defense longer.",
            "They step, I set.",
            "A tidy lawn is a winning lawn.",
            "Grace under gardening.",
            "Watch the gaps, close the gaps.",
            "They are walking into a solved puzzle.",
        ],
        ["PutZombie"] =
        [
            "Chat sent reinforcements? I can handle those too.",
            "Another zombie from chat. Very confident of you.",
            "Chat picked a challenger. I picked its landing spot.",
            "More zombies? Good. The defense needed a warmup.",
            "You can send a crowd. I still own the lawn.",
            "Another guest arrives. The plants are ready.",
            "That one looks determined. So am I.",
            "Chat is making this interesting. I approve.",
            "Fresh zombie incoming. Let me make room in the strategy.",
            "I saw that spawn. No surprises here.",
            "A new face for the lawn. Same result.",
            "You send, I defend. Deal.",
            "Thanks for the extra target practice.",
            "Keep them coming, chat. The lawn eats.",
            "A chat zombie with ambition. Cute.",
            "Spotted and plotted.",
            "Your pick, my placement.",
            "The row just got more interesting.",
            "Another volunteer for the melon test.",
            "Chat zigs, I zag with a wall.",
            "Welcome to the least successful walk of your day, zombie.",
            "I will give that one a proper greeting.",
            "Your spawn, my lawn, my win.",
            "Added to the queue, added to the loss column.",
            "Chat is cooking, but so is my jalapeno.",
            "That zombie has chat support. I have melons.",
            "I see your zombie and raise you a squash.",
            "More feet, more defeat.",
            "A new walker learns quickly.",
            "Chat, you are generous. I am grateful and winning.",
            "That one will not be lonely for long. More are coming and falling.",
            "Send smart, I will still answer.",
            "The chat effect is noted and handled.",
            "Your zombie, your moment. My lawn, my moment longer.",
            "Thanks, stream. Keep testing me.",
            "I file that zombie under handled.",
            "A sturdy pick. A sturdier row.",
            "You call, I plant.",
            "The lawn says hello back.",
            "Even chat zombies wait in line to lose.",
            "Your wave got a plus one.",
            "I will introduce that zombie to my Cactus.",
            "Nice try, neat spawn, same outcome.",
            "Their entrance is my cue.",
            "I love a chat that plays along.",
            "Additional zombie acknowledged and addressed.",
            "Your zombie found the worst lane to find me.",
            "Thanks for keeping the endless endless.",
            "Another data point for the defense.",
            "Chat and I co-host this defense.",
            "Your spawn met my wall. Wall won.",
        ],
        ["PutPlant"] =
        [
            "A plant from chat. Now we are talking strategy.",
            "A little help from chat. I can work with that.",
            "Nice placement from chat. I will build around it.",
            "Another plant joins the team. Good decision.",
            "Chat is helping? I knew you had taste.",
            "That plant looks at home already.",
            "Great pick, chat. Row appreciates it.",
            "A gift from the stream, planted with pride.",
            "Chat plants, I plan. Perfect.",
            "That green is going to work hard.",
            "Welcome to the lawn, new recruit.",
            "Good eye, chat. That tile needed that.",
            "The defense just got deeper.",
            "Chat chose well. I will make it win.",
            "A chat plant with potential. I will realize it.",
            "Nice addition. Immediate impact pending.",
            "That plant and I are already teammates.",
            "From chat to lane in one move.",
            "The grid loves that choice.",
            "A fine plant from fine taste.",
            "Chat is gardening now too.",
            "We are co-planting and winning.",
            "That sprout will see action quickly.",
            "A chat plant that fits the plan.",
            "The lawn approves of that placement.",
            "Helper plant deployed.",
            "Chat contribution accepted and activated.",
            "That plant is about to be busy.",
            "Sun well spent, chat.",
            "A new leaf on the winning side.",
            "Thanks, chat. I will protect it.",
            "Nice, that one saves me a cooldown.",
            "Chat built, I backed it.",
            "We share the shovel, we share the win.",
            "That plant earns its sun today.",
        ],
        ["ClearAllPlants"] =
        [
            "Starting fresh? Bold move. I still have this.",
            "You cleared my board. Watch how fast I rebuild.",
            "Clean slate. The zombies still have a problem.",
            "A full reset? Fine. I like a challenge.",
            "That took my plants. It did not take the plan.",
            "Clear cut, not clear win for them.",
            "Gone is not lost when I replant like this.",
            "Razed and rising.",
            "We rebuild faster than they walk.",
            "Board wiped, bias kept: mine.",
            "Empty lawn, full answer coming.",
            "That was a statement. My response is planting.",
            "You reset the field, not the skill.",
            "The lawn is empty and already winning.",
            "Watch the speed of this rebuild.",
            "This is where planting speed is the stat.",
            "Fresh dirt, familiar dominance.",
            "They cleared plants. I clear doubts.",
            "Reset accepted. Routine resumed.",
            "A momentary blank, a permanent gap closed.",
            "We go from zero to coverage.",
            "No plants? No panic.",
            "This lawn grows back angry.",
            "Clear is just a faster build cue.",
            "You took the garden, I bring it back greener.",
            "Wipe and rebuild, my specialty.",
            "That board will be full before the next wave lands.",
            "Empty tiles are just future walls.",
            "We re-lawn with authority.",
            "That reset will be forgotten by next spawn.",
        ],
        ["KillAllZombies"] =
        [
            "That was efficient. Even I am impressed.",
            "And the lawn goes quiet. Excellent timing.",
            "A clean sweep. I almost feel bad for them.",
            "That is one way to end an argument.",
            "All clear. I will be ready for the next wave.",
            "Zombies cleared, confidence stayed.",
            "A breath, a rebuild, a return.",
            "Silence is golden and temporary.",
            "They vanished, I remain.",
            "Board cleared, standard maintained.",
            "That was a reset they needed.",
            "Nice clear. The next wave is already jealous.",
            "Empty field, full sun, ready again.",
            "The lawn exhales.",
            "That was a power move from chat and I respect it.",
            "Clear and confident.",
            "We enjoy the pause, we prepare in it.",
            "All quiet on the leaf front.",
            "That was satisfying for everyone except them.",
            "A rare quiet. I will fill it with plants.",
            "The zombies left. The plan did not.",
            "Sweep complete, stream pleased.",
            "That clear was clean.",
            "We take the win and the breather.",
            "A moment of peace, then plenty of peas.",
            "The field is free and so is my next plant.",
            "Thanks for the sweep. I will keep the streak.",
            "That was a headline clear.",
            "Gone and sorted.",
            "Ready for the next endless minute.",
            "A zero count looks good on them.",
        ],
        ["SetSun"] =
        [
            "Resources secured. Time to get loud.",
            "Sun is covered. Defense gets the good stuff.",
            "Budget approved. The zombies will notice.",
            "Plenty of sun. Plenty of options.",
            "Sun high, standards higher.",
            "We are funded and dangerous.",
            "The sun bank is open and spending.",
            "Solvent and solving.",
            "Sunny side up for the defense.",
            "That sun is about to become walls and melons.",
            "Five million reasons to win.",
            "Economy strong, lawn stronger.",
            "Sun is not a limit today.",
            "Fully funded foliage.",
            "The treasury is green in both senses.",
            "Sun surplus, zombie deficit.",
            "We have sun to spare and plans to spare none.",
            "Rich in sun, rich in answers.",
            "That sun will be walls within seconds.",
            "Banked and dangerous.",
            "Sun is the easy part. Winning is the next.",
            "Bright lawn, bright future.",
            "The sun says go, I say planted.",
            "All the sun, all the lanes, all the win.",
            "Sun is the fuel, strategy is the engine.",
            "We are sun-secure and zombie-ready.",
            "The budget just got a boost and so did the rows.",
            "Sun up means plants up.",
            "Funds verified, lawn fortified.",
            "We are not out here counting sun, we are spending it.",
            "That sun paid for the next wall already.",
        ],
        ["other"] =
        [
            "Chat made a move. I already have a response.",
            "I saw that. Let us see what happens next.",
            "Interesting choice from chat. I can adapt.",
            "The stream changed the board. I changed the plan.",
            "Effect noted. Lawn adjusted.",
            "You tweak, I tune.",
            "Stream input received and respected.",
            "That effect had style. My reply has substance.",
            "Chat moves, I move better.",
            "We are co-piloting this lawn.",
            "A new variable, same victory aim.",
            "Your effect is my next plan.",
            "The board shifts, the control stays.",
            "Good interplay, stream.",
            "That was a fun swing. My turn.",
            "Effect applied, effect answered.",
            "We keep the lawn responsive.",
            "The chat is part of the defense now.",
            "Every trigger is a chance to show range.",
            "That changed the math, not the result.",
            "Nice curve, still caught.",
            "The stream keeps it spicy. I keep it handled.",
            "We ride whatever wave chat sends.",
            "Adapt and attack, my loop.",
            "Effect logged and leveraged.",
            "Chat tests, lawn answers.",
            "We absorb and advance.",
            "That is why this mode is endless and interesting.",
            "More inputs, more outputs... of peas.",
            "The stream and the lawn in sync.",
            "We turn effects into highlights.",
            "Your move made the highlight longer.",
            "The game within the game is my game.",
            "We are writing this endless together.",
            "Every effect is an invitation to outplant it.",
            "Keep the effects coming, the answer is ready.",
            "That was a chapter. The lawn is the book.",
            "We do not dodge effects, we use them.",
            "Stream pulse, lawn pulse, same beat.",
            "That trigger was the cue I was waiting for.",
            "Another effect, another chance to flex.",
            "The lawn is a live edit and I am the editor.",
            "We keep it endless for a reason.",
            "Chat effect processed, lawn processed faster.",
            "Nice try, we are still here.",
        ],
    };

    internal string Next(string category)
    {
        if (!Lines.TryGetValue(category, out var choices)) choices = Lines["other"];
        var available = choices.Where(line => !_recent.Contains(line)).ToArray();
        if (available.Length == 0) available = choices;
        var result = available[Random.Shared.Next(available.Length)];
        _recent.Enqueue(result);
        while (_recent.Count > 5) _recent.Dequeue();
        return result;
    }
}
